# Site
title:              'Jessica Temporal'
bio:                "Python Developer, Data Scientist and Bachelor in Biomedical Informatics."
description:        "Python Developer, Data Scientist and Bachelor in Biomedical Informatics."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/channel.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
# url:                https://jtemporal.github.io
url_share:          https://jtemporal.com

# Jekyll
lang:               "pt-br"
languages:          ["pt-br", "en"]
permalink:          /:categories/:title/
timezone:           America/Sao_Paulo
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  # analytics:        UA-89599031-1
  # tagmanager:       GTM-KKCR3VG
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              jessicatemporal@gmail.com
# twitter:            jesstemporal
# facebook:           jetemporal
github-url:             jtemporal

#email:
twitter:            jesstemporal
#facebook:           username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           jessicatemporal
#xing:              username
#instagram:          jesstemporal
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Include list
include: [folium, EnJtResume.pdf]

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
